### ISSUE TITLE
Remove old API calls for SEOkicks and Metrics.tools

### ISSUE THREAD

**Issue by toxicdemonWP** [epiphyt/seo-core#23]
the file in /inc/dashboard.class.php contains references to SEOkicks API and Metrics API which are loaded by wpSEO. These must be removed and replaced.

**Comment by toxicdemonWP** [comment]
In the same file on line 246 I also discovered a affiliate link!

**Comment by krafit** [comment]
@toxicdemonWP good catch 💯
